### ISSUE TITLE
Font Awesome extension errors

### ISSUE THREAD

**Issue by wildernessfamily** [R35007/font-awesome-vscode-extension#1]
Hi,
I'm having a problem using FontAwesome extension. After installing, I'm not able to load the icons. Clicking on the FontAwesome icon from the side panel, I receive a blank screen. I click the refresh icon and then receive an error; `font-awesome.refreshView not found`. From the command pallet, I choose, `Download Icon Arcive` and I immediately receive an error; `Command 'Font Awesome: Download Icon Archive' resulted in an error (command 'font-awesome.download' not found)`. Any guidance would be greatly appreciated!

**Things I have tried:**
1. Uninstalled, restarted VSCode.
2. Installed extension, restarted VSCode

**Versions:**
Font Awesome Extension: v3.3.1
VSCode: Version: 1.73.1 (Universal)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z (3 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

**Comment by R35007** [comment]
Hi @wildernessfamily,

I hope you are using the right extension, cz v3.1.1 is the latest version of [Font Awesome](https://marketplace.visualstudio.com/items?itemName=Thinker.font-awesome) is the one I created.

![image](https://user-images.githubusercontent.com/23217228/205677930-ffeffcfa-1380-4c3b-aab1-315a701f7803.png)

If it's the same, please continue down.

Sorry for the trouble. Since I have developed this extension in a windows machine, I haven't caught this issue. 

Thanks for the head up.

Can u pls follow the below steps and send me a screenshot of the console error.
1.  Open vscode
2.  Go to Help -> Toggle Developer Tools
3. Now take a screenshot of the console error

Thanks,
Siva

**Comment by R35007** [comment]
Hi @wildernessfamily ,

I have given a new fix version. can you please update the extension and try it again.
